---
apiVersion: v1
kind: Namespace
metadata:
  name: cfgmgmt
---
apiVersion: v1
kind: Service
metadata:
  namespace: cfgmgmt
  name: service
spec:
  selector:
    name: app
  ports:
    - port: 8080
      nodePort: 30005
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  namespace: cfgmgmt
  name: application
  labels:
    name: app
spec:
  containers:
    - name: config-mgmt
      image: configmgmt:1.0.0
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
  initContainers:
    - name: git-clone
      image: alpine/git:1.0.4
      command: ['/bin/sh', '-c']
      args: ['git clone --branch v1.0.0 https://github.com/nfrankel/configmgmt-properties.git && mv configmgmt-properties/dev/* /config']
      volumeMounts:
        - name: config
          mountPath: /config
  volumes:
    - name: config
      emptyDir: {}
