---
apiVersion: v1
kind: Namespace
metadata:
  name: cfgmgmt
---
apiVersion: v1
kind: Service
metadata:
  namespace: cfgmgmt
  name: service
spec:
  selector:
    name: app
  ports:
    - port: 8080
      nodePort: 30005
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  namespace: cfgmgmt
  name: application
  labels:
    name: app
spec:
  serviceAccountName: spring-boot
  containers:
    - name: config-mgmt
      image: configmgmt:1.1.0
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: application
  namespace: cfgmgmt
data:
  app.env.label: Staging
  app.env.color: orange
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-boot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: map-reader
rules:
  - apiGroups: [""]
    resources: ["maps", "pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-maps
  namespace: cfgmgmt
subjects:
  - kind: ServiceAccount
    name: spring-boot
    apiGroup: ""
roleRef:
  kind: Role
  name: map-reader
  apiGroup: rbac.authorization.k8s.io
